
name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest changes and deploy
        run: |
          ssh -o StrictHostKeyChecking=no maudlin@pdx1-shared-a1-41.dreamhost.com 'cd /home/maudlin/ridley.co/mindmeld && git pull && ./deploy.sh'
