name: Sync to deploy branch

on:
  push:
    branches: [main]

jobs:
  deploy-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"

      - name: Copy deployable files
        run: |
          mkdir -p deploy-staging
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='.gitignore' src/ deploy-staging/

      
      - name: Push to deploy branch
        run: |
          git checkout --orphan deploy-temp
          git reset
          cp -r deploy-staging/* .
          git add .
          git commit -m "Deploy from commit $GITHUB_SHA"
          git push --force origin HEAD:deploy
