name: Report deployment for Jira

on:
  push:
    branches:
      - main

permissions:
  deployments: write
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment
        id: create_deploy
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.sha }}

      - name: Mark deployment as finished
        if: always() # still mark failure if earlier steps fail
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          status: ${{ job.status }} # success, failure, or cancelled
          deployment_id: ${{ steps.create_deploy.outputs.deployment_id }}
          env_url: https://mind-meld.co
          auto_inactive: false
